### ISSUE TITLE
Platform

### ISSUE THREAD

**Issue by santhanam87** [santhanam87/darthmaul#35]
All the platform related issuess will be handled as part of this epic

- [ ] [Webpack] Font import is not working 
- [ ] [Webpack] Webpack config files should be split up into server and client
- [ ] Storybook integration

**Comment by santhanam87** [comment]
- [ ] Font import is not working
- [ ] Webpack config files should be split up into server and client
