### ISSUE TITLE
List View

### ISSUE THREAD

**Issue by santhanam87** [santhanam87/darthmaul#5]
### Design Inspiration

![Image](https://user-images.githubusercontent.com/398747/188544743-9ac019d8-2777-4ca2-b603-aa7e37ea131f.png)

### Activities

- [x] #6
- [x] #10
- [x] #9
- [x] #13
- [x] React thumb component.
- [x] React detail component.
- [x] React thumb detail container component
- [x] Testing

**Comment by santhanam87** [comment]
Closing this with basic integrations.
